import {
  GENERATOR_METADATA_VERSION,
  type GeneratorMetadata,
  parseGeneratorMetadata,
  type PostgresColumn,
} from "@supabase/postgrest-typegen";

const column = (
  overrides: Partial<PostgresColumn> & Pick<PostgresColumn, "name" | "id">,
): PostgresColumn =>
  ({
    table_id: 1,
    schema: "public",
    table: "tickets",
    ordinal_position: 1,
    default_value: null,
    data_type: "text",
    format: "text",
    type_schema: "pg_catalog",
    is_identity: false,
    identity_generation: null,
    is_generated: false,
    is_nullable: false,
    is_updatable: true,
    is_unique: false,
    enums: [],
    check: null,
    comment: null,
    ...overrides,
  }) as PostgresColumn;

const relation = {
  rls_enabled: false,
  rls_forced: false,
  replica_identity: "DEFAULT",
  bytes: 0,
  size: "0 bytes",
  live_rows_estimate: 0,
  dead_rows_estimate: 0,
  comment: null,
} as const;

/**
 * Two schemas, two tables with a foreign key, a view, an enum, a composite
 * type and a function, listed out of canonical order on purpose so tests can
 * show the registry sorts before generating.
 */
export const unsortedMetadata: GeneratorMetadata = parseGeneratorMetadata({
  version: GENERATOR_METADATA_VERSION,
  schemas: [
    { id: 2, name: "public", owner: "postgres" },
    { id: 3, name: "inventory", owner: "postgres" },
  ],
  tables: [
    { id: 1, schema: "public", name: "tickets", ...relation },
    { id: 4, schema: "public", name: "users", ...relation },
    { id: 5, schema: "inventory", name: "items", ...relation },
  ],
  foreignTables: [],
  views: [
    {
      id: 6,
      schema: "public",
      name: "open_tickets",
      is_updatable: false,
      is_insert_enabled: false,
      is_update_enabled: false,
      comment: null,
    },
  ],
  materializedViews: [],
  columns: [
    column({
      id: "1.2",
      name: "status",
      ordinal_position: 2,
      data_type: "USER-DEFINED",
      format: "user_status",
      type_schema: "public",
      enums: ["ACTIVE", "INACTIVE"],
      default_value: "'ACTIVE'::user_status",
    }),
    column({
      id: "1.1",
      name: "id",
      data_type: "bigint",
      format: "int8",
      is_identity: true,
      identity_generation: "ALWAYS",
    }),
    column({
      id: "1.3",
      name: "owner_id",
      ordinal_position: 3,
      data_type: "bigint",
      format: "int8",
      is_nullable: true,
    }),
    column({
      id: "4.1",
      table_id: 4,
      table: "users",
      name: "id",
      data_type: "bigint",
      format: "int8",
      is_identity: true,
      identity_generation: "BY DEFAULT",
    }),
    column({
      id: "4.2",
      table_id: 4,
      table: "users",
      name: "email",
      ordinal_position: 2,
      is_unique: true,
    }),
    column({
      id: "5.1",
      table_id: 5,
      schema: "inventory",
      table: "items",
      name: "sku",
    }),
    column({
      id: "6.1",
      table_id: 6,
      table: "open_tickets",
      name: "id",
      data_type: "bigint",
      format: "int8",
      is_nullable: true,
      is_updatable: false,
    }),
  ],
  primaryKeys: [
    { schema: "public", table_name: "users", name: "id", table_id: 4 },
    { schema: "public", table_name: "tickets", name: "id", table_id: 1 },
  ],
  relationships: [
    {
      foreign_key_name: "tickets_owner_id_fkey",
      schema: "public",
      relation: "tickets",
      columns: ["owner_id"],
      is_one_to_one: false,
      referenced_schema: "public",
      referenced_relation: "users",
      referenced_columns: ["id"],
    },
  ],
  functions: [
    {
      id: 300,
      schema: "public",
      name: "ticket_count",
      language: "sql",
      definition: "select 1",
      complete_statement: "CREATE FUNCTION ...",
      args: [
        { mode: "in", name: "status", type_id: 100, has_default: false },
        { mode: "in", name: "owner", type_id: 20, has_default: true },
      ],
      argument_types: "status user_status, owner bigint",
      identity_argument_types: "status user_status, owner bigint",
      return_type_id: 23,
      return_type: "integer",
      return_type_relation_id: null,
      is_set_returning_function: false,
      prorows: 0,
      behavior: "STABLE",
      security_definer: false,
      config_params: null,
    },
  ],
  types: [
    {
      id: 100,
      name: "user_status",
      schema: "public",
      format: "user_status",
      enums: ["ACTIVE", "INACTIVE"],
      attributes: [],
      comment: null,
      type_relation_id: null,
    },
    {
      id: 25,
      name: "text",
      schema: "pg_catalog",
      format: "text",
      enums: [],
      attributes: [],
      comment: null,
      type_relation_id: null,
    },
    {
      id: 23,
      name: "int4",
      schema: "pg_catalog",
      format: "int4",
      enums: [],
      attributes: [],
      comment: null,
      type_relation_id: null,
    },
    {
      id: 20,
      name: "int8",
      schema: "pg_catalog",
      format: "int8",
      enums: [],
      attributes: [],
      comment: null,
      type_relation_id: null,
    },
    {
      id: 200,
      name: "address",
      schema: "public",
      format: "address",
      enums: [],
      attributes: [
        { name: "street", type_id: 25 },
        { name: "city", type_id: 25 },
      ],
      comment: null,
      type_relation_id: 200,
    },
  ],
});
