import { readFileSync, readdirSync, existsSync } from "node:fs";
import { join, resolve, relative } from "node:path";
import type { ParsedSymbol, ParseResult } from "./ts-parser.js";
import { loadIgnore, type Ignore } from "./parse-ignore.js";

export type { ParsedSymbol, ParseResult };

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

// Files generated by build_runner — not meaningful public API
const GENERATED_FILE_RE = /\.(g|freezed|gr|config|mocks)\.dart$/;

// Words that can appear before `(` on a declaration line but are not method names
const SKIP_KW = new Set([
  "if", "else", "for", "while", "do", "switch", "try", "catch", "finally",
  "return", "throw", "assert", "super", "new", "await", "yield", "operator",
  "Function", // Dart built-in function type, not a method name
]);

interface Context {
  name: string;   // possibly dotted, e.g. "SupabaseClient.Configuration"
  depth: number;  // brace depth after entering this context
}

function findDartFiles(dir: string, root: string, ig: Ignore): string[] {
  const results: string[] = [];
  try {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      if (entry.name.startsWith(".")) continue;
      const full = join(dir, entry.name);
      const rel = relative(root, full);
      if (entry.isDirectory()) {
        if (ig.ignores(rel + "/")) continue;
        results.push(...findDartFiles(full, root, ig));
      } else if (
        entry.isFile() &&
        entry.name.endsWith(".dart") &&
        !GENERATED_FILE_RE.test(entry.name)
      ) {
        if (ig.ignores(rel)) continue;
        results.push(full);
      }
    }
  } catch { /* ignore unreadable dirs */ }
  return results;
}

// ---------------------------------------------------------------------------
// Single-file parser
// ---------------------------------------------------------------------------

// Anchored to start of trimmed line to avoid matching `class` inside strings.
// Handles: class, abstract class, final class, sealed class, mixin, mixin class, enum.
// The type name is the word following the final keyword in the declaration.
const TYPE_DECL_RE = /^(?:(?:abstract|final|base|sealed|interface)\s+)*(?:mixin\s+class|class|enum|mixin)\s+(\w+)/;
// Named extension: `extension FooExtension on SomeType`
const EXT_DECL_RE = /^extension\s+(\w+)\s+on\b/;
// Top-level typedef declaration
const TYPEDEF_RE = /^typedef\s+(\w+)\b/;

// Returns the method or constructor name from a declaration line, or null if
// the line is not a method declaration (e.g. a field initializer or assignment).
function extractMethodName(trimmed: string): string | null {
  const firstParen = trimmed.indexOf("(");
  if (firstParen < 0) return null;

  // Presence of `=` before the first `(` indicates a field initializer or
  // assignment expression, not a declaration.
  const eqIdx = trimmed.indexOf("=");
  if (eqIdx >= 0 && eqIdx < firstParen) return null;

  // The method/constructor name is the last identifier before the first `(`.
  const before = trimmed.slice(0, firstParen);
  const m = before.match(/(\w+)\s*$/);
  return m ? m[1] : null;
}

export function extractFromSource(source: string, relPath: string): ParsedSymbol[] {
  const symbols: ParsedSymbol[] = [];
  const contextStack: Context[] = [];
  let depth = 0;
  // True while we're parsing the right-hand side of a `=>` arrow expression that
  // spans multiple lines. Continuation lines look like class-body declarations but
  // aren't — suppressing extraction prevents false symbols from constructor calls
  // embedded in toString(), copyWith(), etc.
  let inArrowContinuation = false;

  for (const rawLine of source.split("\n")) {
    // Strip line comments (// and ///)
    const commentIdx = rawLine.indexOf("//");
    const line = commentIdx >= 0 ? rawLine.slice(0, commentIdx) : rawLine;
    const trimmed = line.trim();

    if (!trimmed) continue;

    const opens = countChar(line, "{");
    const closes = countChar(line, "}");

    const topCtx = contextStack.length > 0 ? contextStack[contextStack.length - 1] : null;
    const currentType = topCtx?.name ?? "";
    // Gate member extraction to class-body depth only — prevents extracting
    // method calls inside method bodies as false symbols.
    const atClassBody = topCtx !== null && depth === topCtx.depth;

    // Arrow-continuation: if the PREVIOUS class-body line ended with `=>`, the
    // current line is the right-hand side of a multi-line arrow function. Suppress
    // member extraction so constructor calls in toString()/copyWith() bodies don't
    // produce false symbols. A continuation ends at `;` or when brace depth changes.
    const skipAsContinuation = inArrowContinuation;
    if (inArrowContinuation && (trimmed.endsWith(";") || opens !== closes)) {
      inArrowContinuation = false;
    }

    // --- Type declarations ---
    const typeM = trimmed.match(TYPE_DECL_RE);
    const extM = !typeM && trimmed.match(EXT_DECL_RE);
    const typedefM = !typeM && !extM && !currentType && trimmed.match(TYPEDEF_RE);

    if (typeM) {
      const typeName = typeM[1];
      if (!typeName.startsWith("_")) {
        const qualified = currentType ? `${currentType}.${typeName}` : typeName;
        symbols.push({ name: qualified, kind: "class", file: relPath });
      }
    } else if (typedefM) {
      const name = typedefM[1];
      if (!name.startsWith("_")) {
        symbols.push({ name, kind: "variable", file: relPath });
      }
    }

    // --- Class members (only at immediate class-body depth) ---
    // Skip annotation lines: `@Annotation(params)` on its own line looks like a
    // declaration but is not. Parameterised annotations without this guard would
    // emit the annotation name as a false method symbol.
    if (atClassBody && !typeM && !extM && !trimmed.startsWith("@") && !skipAsContinuation) {
      // Getter: `get propertyName`
      const getterM = trimmed.match(/\bget\s+(\w+)\b/);
      // Setter: `set propertyName(`
      const setterM = !getterM && trimmed.match(/\bset\s+(\w+)\s*\(/);
      // Factory constructor: `factory ClassName` or `factory ClassName.namedCtor`
      const factoryM = !getterM && !setterM && trimmed.match(/\bfactory\s+([\w.]+)\s*(?:<[^>]*>)?\s*\(/);

      if (getterM) {
        const name = getterM[1];
        if (!name.startsWith("_")) {
          symbols.push({ name: `${currentType}.${name}`, kind: "property", file: relPath });
        }
      } else if (setterM) {
        const name = setterM[1];
        if (!name.startsWith("_")) {
          symbols.push({ name: `${currentType}.${name}`, kind: "property", file: relPath });
        }
      } else if (factoryM) {
        // Strip the class name prefix that Dart requires on factory constructors.
        // e.g. inside `SupabaseClient`: `factory SupabaseClient.withDefaults()` → emit `.withDefaults`
        const simpleClass = currentType.split(".").pop() ?? currentType;
        const prefix = simpleClass + ".";
        const fullName = factoryM[1];
        const name = fullName.startsWith(prefix)
          ? fullName.slice(prefix.length)  // named ctor: ClassName.name → name
          : fullName;                       // default factory: ClassName → ClassName
        if (!name.startsWith("_")) {
          symbols.push({ name: `${currentType}.${name}`, kind: "method", file: relPath });
        }
      } else {
        const name = extractMethodName(trimmed);
        if (name && !name.startsWith("_") && !SKIP_KW.has(name)) {
          symbols.push({ name: `${currentType}.${name}`, kind: "method", file: relPath });
        }
      }
    }

    // After extracting, mark the next line as an arrow continuation if this
    // class-body line ends with `=>` (multi-line arrow function).
    if (atClassBody && trimmed.endsWith("=>")) inArrowContinuation = true;

    // --- Update depth ---
    depth += opens - closes;

    // Pop contexts that ended when closes brought depth below their enter depth
    while (contextStack.length > 0 && contextStack[contextStack.length - 1].depth > depth) {
      contextStack.pop();
    }

    // Push new context if a type or named extension body opens on this line
    if (opens > closes) {
      if (typeM) {
        const typeName = typeM[1];
        if (!typeName.startsWith("_")) {
          const qualified = currentType ? `${currentType}.${typeName}` : typeName;
          contextStack.push({ name: qualified, depth });
        }
      } else if (extM) {
        contextStack.push({ name: extM[1], depth });
      }
    }
  }

  return symbols;
}

// ---------------------------------------------------------------------------
// Project-level entry point
// ---------------------------------------------------------------------------

export function parseDartProject(projectRoot: string): ParseResult {
  const root = resolve(projectRoot);
  const ig = loadIgnore(root);
  // Dart convention: lib/ holds all public library code
  const libDir = join(root, "lib");
  const scanRoot = existsSync(libDir) ? libDir : root;

  const files = findDartFiles(scanRoot, root, ig);
  const symbols: ParsedSymbol[] = [];

  for (const file of files) {
    const source = readFileSync(file, "utf8");
    const relPath = relative(root, file);
    symbols.push(...extractFromSource(source, relPath));
  }

  return { symbols };
}

// ---------------------------------------------------------------------------
// Utility
// ---------------------------------------------------------------------------

function countChar(s: string, ch: string): number {
  let count = 0;
  for (let i = 0; i < s.length; i++) {
    if (s[i] === ch) count++;
  }
  return count;
}
